# Generated by Django 5.0.7 on 2024-07-29 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter Category...", max_length=100, unique=True
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("level", models.IntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orm_app.category",
                    ),
                ),
            ],
        ),
        migrations.RunSQL("""
        ALTER TABLE orm_app_category
        ADD CONSTRAINT  orm_app_category_chk_empty_name
        CHECK (name <> '' AND name is NOT NULL)             
        """),
    ]
