# Generated by Django 5.0.7 on 2024-07-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm_app", "0001_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonalEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "orm_app_seasonal_event",
            },
        ),
        migrations.RunSQL("""
        ALTER TABLE orm_app_seasonal_event
        ADD CONSTRAINT  orm_app_seasonal_event_chk_empty_name
        CHECK (name <> '' AND name is NOT NULL)             
        """),
        migrations.RunSQL("""
            CREATE OR REPLACE FUNCTION lowercase_name_trigger()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.name := LOWER(NEW.name);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
             
            CREATE TRIGGER  seasonal_event_lowercase_name_trigger
            BEFORE INSERT OR UPDATE ON orm_app_seasonal_event
            FOR EACH ROW
            EXECUTE FUNCTION lowercase_name_trigger();
            """),
    ]
