# Generated by Django 5.0.7 on 2024-07-30 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm_app", "0002_seasonal_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("level", models.IntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orm_app.producttype",
                    ),
                ),
            ],
            options={
                "db_table": "orm_app_product_type",
            },
        ),
        migrations.RunSQL("""
        ALTER TABLE orm_app_product_type
        ADD CONSTRAINT  orm_app_product_type_chk_empty_name
        CHECK (name <> '' AND name is NOT NULL)             
        """),
        migrations.RunSQL("""
            CREATE OR REPLACE FUNCTION lowercase_name_trigger()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.name := LOWER(NEW.name);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
             
            CREATE TRIGGER  product_type_lowercase_name_trigger
            BEFORE INSERT OR UPDATE ON orm_app_product_type
            FOR EACH ROW
            EXECUTE FUNCTION lowercase_name_trigger();
            """),
        migrations.RunSQL("""
        ALTER TABLE orm_app_product_type
        ADD CONSTRAINT  orm_app_product_type_chk_unique_name_level
        UNIQUE (name,level);             
        """),
        migrations.RunSQL("""
        ALTER TABLE orm_app_product_type
        ADD CONSTRAINT  orm_app_product_type_chk_level_range
        CHECK (level >=0 AND level <= 10);             
        """),
    ]
