# Generated by Django 5.0.7 on 2024-07-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm_app", "0003_product_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.RunSQL("""
        ALTER TABLE orm_app_attribute
        ADD CONSTRAINT  orm_app_attribute_chk_empty_name
        CHECK (name <> '' AND name is NOT NULL)             
        """),
        migrations.RunSQL("""
            CREATE OR REPLACE FUNCTION lowercase_name_trigger()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.name := LOWER(NEW.name);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
             
            CREATE TRIGGER  attribute_lowercase_name_trigger
            BEFORE INSERT OR UPDATE ON orm_app_attribute
            FOR EACH ROW
            EXECUTE FUNCTION lowercase_name_trigger();
            """),
    ]
