# Generated by Django 5.0.7 on 2024-07-30 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm_app", "0005_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attribute_value", models.CharField(max_length=100)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orm_app.attribute",
                    ),
                ),
            ],
            options={
                "db_table": "orm_app_attribute_value",
            },
        ),
        migrations.RunSQL("""
        ALTER TABLE orm_app_attribute_value
        ADD CONSTRAINT  orm_app_attribute_value_chk_unique_name_level
        UNIQUE (attribute_id,attribute_value);             
        """),
    ]
