# Generated by Django 5.0.7 on 2024-07-30 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm_app", "0007_product_line"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alternative_text", models.CharField(max_length=100)),
                ("url", models.ImageField(upload_to="")),
                ("order", models.IntegerField()),
                (
                    "product_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orm_app.productline",
                    ),
                ),
            ],
            options={
                "db_table": "orm_app_product_image",
            },
        ),
        migrations.RunSQL("""
        ALTER TABLE orm_app_product_image
        ADD CONSTRAINT  orm_app_product_image_chk_unique_product_order
        UNIQUE (product_line_id,"order");             
        """),
    ]
