# Generated by Django 5.0.7 on 2024-07-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0002_alter_catergory_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catergory',
            options={'verbose_name': 'Inventory Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='catergory',
            name='name',
            field=models.CharField(help_text='Enter Category...', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='catergory',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
