# Generated by Django 5.0.7 on 2024-07-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0003_alter_catergory_options_alter_catergory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
