# Generated by Django 5.0.7 on 2024-07-24 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0005_alter_product_catergory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orm_app.producttype'),
        ),
    ]
