# Generated by Django 5.0.7 on 2024-07-24 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0006_alter_producttype_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seasonal_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orm_app.seasonalevents'),
        ),
    ]
