# Generated by Django 5.0.7 on 2024-07-24 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0007_alter_product_seasonal_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seasonal_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orm_app.seasonalevent'),
        ),
        migrations.DeleteModel(
            name='SeasonalEvents',
        ),
    ]
