# Generated by Django 5.0.7 on 2024-07-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0008_seasonalevent_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catergory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='catergory',
            new_name='category',
        ),
    ]
