# Generated by Django 5.0.7 on 2024-07-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0009_rename_catergory_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributevalue',
            old_name='attributevalue',
            new_name='attribute_value',
        ),
    ]
