# Generated by Django 5.0.7 on 2024-07-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0010_rename_attributevalue_attributevalue_attribute_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productline',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
