# Generated by Django 5.0.7 on 2024-07-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0012_remove_productline_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='name',
        ),
    ]
